import type { Metadata } from "next";
import Navbar from "./components/navbar";
import { Bellefair, Barlow_Condensed, Barlow } from "next/font/google";
import "./globals.css";

const bellefair = Bellefair({
  weight: "400",
  variable: "--bellefair",
});

const barlowCondensed = Barlow_Condensed({
  weight: "400",
  variable: "--barlowCondensed",
});

const barlow = Barlow({
  weight: "400",
  variable: "--barlow",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${bellefair.variable} ${barlow.variable} ${barlowCondensed.variable} h-full antialiased`}
    >
      <body>
        <main className="font-barlow">
         <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
